const db = globalThis.__B44_DB__ || { auth:{ isAuthenticated: async()=>false, me: async()=>null }, entities:new Proxy({}, { get:()=>({ filter:async()=>[], get:async()=>null, create:async()=>({}), update:async()=>({}), delete:async()=>({}) }) }), integrations:{ Core:{ UploadFile:async()=>({ file_url:'' }) } } };

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";

import { jsPDF } from "jspdf";
import { FileText, Download, Loader2, CheckCircle } from "lucide-react";
import { motion } from "framer-motion";

const SECTIONS = [
  { key: "targets", label: "Targets / Subjects" },
  { key: "findings", label: "Dossier Findings" },
  { key: "watchlist", label: "Watchlist Entries" },
  { key: "alerts", label: "Intel Alerts" },
  { key: "memories", label: "Key Intel Notes" },
];

export default function ReportGenerator() {
  const [selected, setSelected] = useState(new Set(["targets", "findings", "watchlist", "alerts"]));
  const [title, setTitle] = useState("OSINT Investigation Report");
  const [analyst, setAnalyst] = useState("JARVIS");
  const [generating, setGenerating] = useState(false);
  const [done, setDone] = useState(false);

  const { data: targets = [] } = useQuery({ queryKey: ["targets"], queryFn: () => db.entities.Target.list() });
  const { data: findings = [] } = useQuery({ queryKey: ["dossier-findings"], queryFn: () => db.entities.DossierFinding.list() });
  const { data: watchlist = [] } = useQuery({ queryKey: ["watchlist"], queryFn: () => db.entities.Watchlist.list() });
  const { data: alerts = [] } = useQuery({ queryKey: ["intel-alerts"], queryFn: () => db.entities.IntelAlert.list() });
  const { data: memories = [] } = useQuery({ queryKey: ["memories"], queryFn: () => db.entities.Memory.list() });

  const toggle = (k) => setSelected(prev => {
    const next = new Set(prev);
    next.has(k) ? next.delete(k) : next.add(k);
    return next;
  });

  const generatePDF = async () => {
    setGenerating(true);
    setDone(false);
    await new Promise(r => setTimeout(r, 400));

    const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const W = 210;
    const margin = 18;
    let y = margin;

    // ── Header ──────────────────────────────────────────────
    doc.setFillColor(8, 2, 4);
    doc.rect(0, 0, W, 40, "F");
    doc.setTextColor(220, 60, 60);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin, 18);
    doc.setFontSize(8);
    doc.setTextColor(160, 80, 80);
    doc.text(`ANALYST: ${analyst}  |  DATE: ${new Date().toISOString().slice(0, 10)}  |  CLASSIFICATION: CONFIDENTIAL`, margin, 27);
    doc.setDrawColor(220, 60, 60);
    doc.setLineWidth(0.5);
    doc.line(margin, 32, W - margin, 32);
    doc.setTextColor(120, 60, 60);
    doc.setFontSize(7);
    doc.text("Generated by JARVIS Intelligence Platform — For Authorised Use Only", margin, 37);
    y = 48;

    const addSection = (heading, rows) => {
      if (y > 260) { doc.addPage(); y = margin; }
      doc.setFillColor(20, 6, 6);
      doc.rect(margin, y, W - margin * 2, 7, "F");
      doc.setTextColor(220, 80, 80);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text(heading.toUpperCase(), margin + 3, y + 4.8);
      y += 10;

      if (!rows.length) {
        doc.setTextColor(120, 80, 80);
        doc.setFontSize(8);
        doc.setFont("helvetica", "italic");
        doc.text("No records found.", margin + 3, y);
        y += 8;
        return;
      }

      rows.forEach((row) => {
        if (y > 270) { doc.addPage(); y = margin; }
        doc.setFillColor(14, 4, 4);
        doc.rect(margin, y, W - margin * 2, 0.3, "F");
        y += 2;
        Object.entries(row).forEach(([k, v]) => {
          if (!v || v === "undefined") return;
          if (y > 270) { doc.addPage(); y = margin; }
          doc.setTextColor(160, 100, 100);
          doc.setFontSize(7.5);
          doc.setFont("helvetica", "bold");
          doc.text(`${k}:`, margin + 3, y);
          doc.setTextColor(200, 160, 160);
          doc.setFont("helvetica", "normal");
          const lines = doc.splitTextToSize(String(v), W - margin * 2 - 35);
          doc.text(lines, margin + 30, y);
          y += lines.length * 4.5;
        });
        y += 3;
      });
      y += 4;
    };

    if (selected.has("targets")) {
      addSection("Targets / Subjects", targets.map(t => ({
        Name: t.name, Aliases: t.aliases?.join(", "), Location: t.location,
        Email: t.email, Phone: t.phone, Status: t.status,
        Confidence: t.confidence_score ? `${t.confidence_score}/10` : undefined,
        Notes: t.notes,
      })));
    }

    if (selected.has("findings")) {
      addSection("Dossier Findings", findings.slice(0, 60).map(f => ({
        Target: f.target_id, Layer: f.layer, "Data Point": f.data_point,
        Value: f.value, Source: f.source,
        Confidence: f.confidence ? `${f.confidence}/10` : undefined,
      })));
    }

    if (selected.has("watchlist")) {
      addSection("Watchlist Entries", watchlist.map(w => ({
        Name: w.name, Type: w.type, Status: w.status,
        Keywords: w.alert_keywords?.join(", "), Notes: w.notes,
      })));
    }

    if (selected.has("alerts")) {
      addSection("Intel Alerts", alerts.map(a => ({
        Title: a.title, Source: a.source, Severity: a.severity, Body: a.body,
      })));
    }

    if (selected.has("memories")) {
      addSection("Key Intel Notes", memories.filter(m => m.active).map(m => ({
        Title: m.title, Type: m.type, Content: m.content,
        Tags: m.tags?.join(", "), Importance: m.importance ? `${m.importance}/10` : undefined,
      })));
    }

    // Footer
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setTextColor(80, 40, 40);
      doc.text(`Page ${i} of ${pages}  |  JARVIS Intelligence Platform`, margin, 292);
    }

    doc.save(`JARVIS_Report_${Date.now()}.pdf`);
    setGenerating(false);
    setDone(true);
    setTimeout(() => setDone(false), 3000);
  };

  return (
    <div className="h-full overflow-y-auto p-6">
      <div className="max-w-2xl mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center gap-3">
          <FileText className="w-5 h-5" style={{ color: "rgba(255,80,80,0.6)" }} />
          <h1 className="text-sm font-heading tracking-widest" style={{ fontFamily: "'Orbitron', sans-serif", color: "rgba(255,100,100,0.7)", fontWeight: 700 }}>
            REPORT GENERATOR
          </h1>
        </div>

        {/* Title & Analyst */}
        <div className="space-y-3 rounded-xl p-4" style={{ background: "rgba(12,4,4,0.9)", border: "1px solid rgba(200,30,30,0.15)" }}>
          <div>
            <label className="text-[9px] font-mono tracking-widest" style={{ color: "rgba(200,80,80,0.5)" }}>REPORT TITLE</label>
            <input
              value={title}
              onChange={e => setTitle(e.target.value)}
              className="w-full mt-1 bg-transparent border-b text-sm font-mono text-foreground/80 focus:outline-none pb-1"
              style={{ borderColor: "rgba(200,30,30,0.2)" }}
            />
          </div>
          <div>
            <label className="text-[9px] font-mono tracking-widest" style={{ color: "rgba(200,80,80,0.5)" }}>ANALYST</label>
            <input
              value={analyst}
              onChange={e => setAnalyst(e.target.value)}
              className="w-full mt-1 bg-transparent border-b text-sm font-mono text-foreground/80 focus:outline-none pb-1"
              style={{ borderColor: "rgba(200,30,30,0.2)" }}
            />
          </div>
        </div>

        {/* Section selector */}
        <div className="rounded-xl p-4 space-y-2" style={{ background: "rgba(12,4,4,0.9)", border: "1px solid rgba(200,30,30,0.15)" }}>
          <p className="text-[9px] font-mono tracking-widest mb-3" style={{ color: "rgba(200,80,80,0.5)" }}>INCLUDE SECTIONS</p>
          {SECTIONS.map(s => {
            const on = selected.has(s.key);
            return (
              <button key={s.key} onClick={() => toggle(s.key)}
                className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-left transition-all"
                style={{ background: on ? "rgba(200,30,30,0.1)" : "transparent", border: `1px solid ${on ? "rgba(200,30,30,0.25)" : "rgba(200,30,30,0.08)"}` }}>
                <div className="w-3.5 h-3.5 rounded border flex items-center justify-center flex-shrink-0"
                  style={{ borderColor: on ? "rgba(255,80,80,0.5)" : "rgba(200,80,80,0.2)", background: on ? "rgba(255,60,60,0.2)" : "transparent" }}>
                  {on && <div className="w-1.5 h-1.5 rounded-sm" style={{ background: "rgba(255,80,80,0.8)" }} />}
                </div>
                <span className="text-xs font-mono" style={{ color: on ? "rgba(255,160,160,0.8)" : "rgba(180,80,80,0.4)" }}>{s.label}</span>
              </button>
            );
          })}
        </div>

        {/* Generate button */}
        <motion.button
          whileTap={{ scale: 0.97 }}
          onClick={generatePDF}
          disabled={generating || selected.size === 0}
          className="w-full py-3 rounded-xl font-mono text-sm tracking-widest flex items-center justify-center gap-2 transition-all"
          style={{
            background: done ? "rgba(60,180,80,0.15)" : "rgba(200,30,30,0.15)",
            border: `1px solid ${done ? "rgba(60,180,80,0.3)" : "rgba(200,30,30,0.3)"}`,
            color: done ? "rgba(120,255,140,0.8)" : "rgba(255,120,120,0.8)",
          }}>
          {generating ? <Loader2 className="w-4 h-4 animate-spin" /> : done ? <CheckCircle className="w-4 h-4" /> : <Download className="w-4 h-4" />}
          {generating ? "COMPILING..." : done ? "PDF DOWNLOADED" : "GENERATE PDF REPORT"}
        </motion.button>

        <p className="text-[9px] font-mono text-center" style={{ color: "rgba(160,80,80,0.3)" }}>
          Report compiles live data from your entities — targets, findings, watchlist, alerts, and notes.
        </p>
      </div>
    </div>
  );
}